[versions]
androidxtiles = "1.1.0-alpha01"
compose = "1.2.0-alpha02"
gradlePlugin = "7.1.1"
kotlin = "1.6.10"
wearcompose = "1.0.0-alpha15"
composesnapshot = "-" # a single character = no snapshot

[libraries]
affectedmoduledetector = "com.dropbox.affectedmoduledetector:affectedmoduledetector:0.1.3"
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
androidx-activity-compose = "androidx.activity:activity-compose:1.4.0"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.4.0"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
androidx-wear = "androidx.wear:wear:1.2.0"
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidxtiles" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.6.10"
espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
junit = "junit:junit:4.13.2"
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
metalavaGradle = "me.tylerbwong.gradle:metalava-gradle:0.2.1"
wearcompose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearcompose" }
wearcompose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearcompose" }
wearcompose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearcompose" }
