[versions]
affectedmoduledetector = "0.1.5"
androidx-concurrent = "1.1.0"
androidx-media3 = "1.0.0-beta01"
androidx-test-ext = "1.1.3"
androidx-test = "1.4.0"
androidxActivity = "1.5.0-rc01"
androidxCore = "1.8.0"
androidxFragment = "1.5.0-rc01"
androidxLifecycle = "2.5.0-rc02"
androidxNavigation = "2.5.0-rc02"
androidxWear = "1.2.0"
androidxtiles = "1.1.0-alpha08"
app-cash-paparazzi = "1.0.0"
benManes = "0.42.0"
com-squareup-okhttp3 = "4.10.0"
com-squareup-retrofit2 = "2.9.0"
compose = "1.2.0-rc02"
composesnapshot = "-"
dokka = "1.5.0"
espresso = "3.4.0"
gradlePlugin = "7.2.1"
io-coil-kt = "2.1.0"
junit = "4.13.2"
kotlin = "1.6.21"
kotlinxCoroutine = "1.6.3"
ktlint = "0.42.1"
metalava = "0.2.1"
moshi = "1.13.0"
room = "2.4.2"
spotless = "6.7.2"
truth = "1.1.3"
versionCatalogUpdate = "0.5.1"
wearcompose = "1.0.0-rc02"

[libraries]
accompanist-pager = "com.google.accompanist:accompanist-pager:0.24.11-rc"
affectedmoduledetector = { module = "com.dropbox.affectedmoduledetector:affectedmoduledetector", version.ref = "affectedmoduledetector" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-annotation = "androidx.annotation:annotation:1.4.0"
androidx-concurrent-future = { module = "androidx.concurrent:concurrent-futures", version.ref = "androidx-concurrent" }
androidx-concurrent-future-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "androidx-concurrent" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-corektx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodelktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "androidx-media3" }
androidx-media3-datasourceokhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-exoplayerdash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "androidx-media3" }
androidx-media3-exoplayerhls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-exoplayerrtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "androidx-media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx-media3" }
androidx-media3-testutils = { module = "androidx.media3:media3-test-utils", version.ref = "androidx-media3" }
androidx-media3-testutils-robolectric = { module = "androidx.media3:media3-test-utils-robolectric", version.ref = "androidx-media3" }
androidx-mediarouter = "androidx.mediarouter:mediarouter:1.3.0"
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-palette-ktx = "androidx.palette:palette-ktx:1.0.0"
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-espressocore = "androidx.test.espresso:espresso-core:3.4.0"
androidx-test-ext = "androidx.test.ext:junit:1.1.3"
androidx-test-ext-ktx = "androidx.test.ext:junit-ktx:1.1.3"
androidx-test-exttruth = "androidx.test.ext:truth:1.4.0"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test" }
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidxWear" }
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidxtiles" }
androidx-wear-tiles-material = { module = "androidx.wear.tiles:tiles-material", version.ref = "androidxtiles" }
androidx-wear-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidxtiles" }
androidx-wear-tiles-testing = { module = "androidx.wear.tiles:tiles-testing", version.ref = "androidxtiles" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "io-coil-kt" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "io-coil-kt" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material-iconscore = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.20.0"
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = "org.jetbrains.kotlin:kotlin-stdlib:1.6.21"
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutine" }
lottie-compose = "com.airbnb.android:lottie-compose:5.2.0"
metalavaGradle = { module = "me.tylerbwong.gradle:metalava-gradle", version.ref = "metalava" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "app-cash-paparazzi" }
paparazziPlugin = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "app-cash-paparazzi" }
retrofit2-convertermoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "com-squareup-retrofit2" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
robolectric = "org.robolectric:robolectric:4.8.1"
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
wearcompose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearcompose" }
wearcompose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearcompose" }
wearcompose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearcompose" }

[plugins]
benManes = { id = "com.github.ben-manes.versions", version.ref = "benManes" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinGradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
