[versions]
accompanist = "0.34.0"
androidx-benchmark = "1.2.4"
androidx-complications-data = "1.2.1"
androidx-constraintlayout-compose = "1.0.1"
androidx-compose-material = "1.7.0-alpha07"
androidx-concurrent = "1.1.0"
androidx-datastore = "1.1.1"
androidx-health-services = "1.0.0-rc02"
androidx-hilt = "1.2.0"
androidx-media3 = "1.3.1"
androidx-test-espresso = "3.6.0-alpha04"
androidx-test-ext = "1.2.0-alpha04"
androidx-test-runner = "1.6.0-alpha07"
androidx-tracingPerfetto = "1.0.0"
androidx-tracingPerfettoBinary = "1.0.0"
androidx-wear-watchface = "1.2.1"
androidxActivity = "1.9.0"
androidxCore = "1.13.1"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.7"
androidxPhoneInteractions = "1.1.0-alpha04"
androidxRemoteInteractions = "1.1.0-alpha02"
androidxStartup = "1.1.1"
androidxTracing = "1.2.0"
androidxWear = "1.3.0"
androidxWork = "2.9.0"
androidxprotolayout = "1.1.0"
androidxtiles = "1.3.0"
annotation = "1.0.1"
app-cash-turbine = "1.1.0"
com-squareup-okhttp3 = "5.0.0-alpha.14"
com-squareup-retrofit2 = "2.11.0"
compose = "1.7.0-alpha08"
compose-compiler = "1.5.11"
compose-material3 = "1.3.0-alpha06"
composesnapshot = "-"
dependencyAnalysis = "1.31.0"
dokka = "1.9.20"
googledagger = "2.51.1"
gradlePlugin = "8.4.0"
gradlePublishPlugin = "0.28.0"
io-coil-kt = "2.6.0"
junit = "4.13.2"
kotlin = "1.9.23"
kotlinxCoroutine = "1.8.0"
ksp = "1.9.23-1.0.20"
ktlint = "0.50.0"
metalava = "0.3.5"
moshi = "1.15.1"
okio = "3.9.0"
org-robolectric = "4.12.1"
playServicesAuth = "21.1.0"
protobuf = "4.26.1"
roborazzi = "1.13.0"
room = "2.6.1"
runtimeTracing = "1.0.0-beta01"
spotless = "6.25.0"
tiles-tooling-preview = "1.3.0"
truth = "1.4.2"
wearcompose = "1.4.0-alpha08"
wearToolingPreview = "1.0.0"
appcompat = "1.6.1"
material = "1.11.0"
wearInput = "1.2.0-alpha02"

[libraries]
accompanist-testharness = { module = "com.google.accompanist:accompanist-testharness", version.ref = "accompanist" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-annotation = "androidx.annotation:annotation:1.7.1"
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-complications-data = { module = "androidx.wear.watchface:watchface-complications-data", version.ref = "androidx-complications-data" }
androidx-complications-datasource-ktx = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "androidx-wear-watchface" }
androidx-complications-rendering = { module = "androidx.wear.watchface:watchface-complications-rendering", version.ref = "androidx-wear-watchface" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-concurrent-future = { module = "androidx.concurrent:concurrent-futures", version.ref = "androidx-concurrent" }
androidx-concurrent-future-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "androidx-concurrent" }
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
androidx-corektx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-health-services = { module = "androidx.health:health-services-client", version.ref = "androidx-health-services" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodelktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "androidx-media3" }
androidx-media3-datasourceokhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-exoplayerdash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "androidx-media3" }
androidx-media3-exoplayerhls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-exoplayerrtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "androidx-media3" }
androidx-media3-exoplayerworkmanager = { module = "androidx.media3:media3-exoplayer-workmanager", version.ref = "androidx-media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx-media3" }
androidx-media3-testutils = { module = "androidx.media3:media3-test-utils", version.ref = "androidx-media3" }
androidx-media3-testutils-robolectric = { module = "androidx.media3:media3-test-utils-robolectric", version.ref = "androidx-media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
androidx-mediarouter = "androidx.mediarouter:mediarouter:1.7.0"
androidx-metrics-performance = "androidx.metrics:metrics-performance:1.0.0-beta01"
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-paging = "androidx.paging:paging-compose:3.2.1"
androidx-palette-ktx = "androidx.palette:palette-ktx:1.0.0"
androidx-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtimeTracing" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-espressocore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "androidxTracing" }
androidx-tracing-perfetto = { module = "androidx.tracing:tracing-perfetto", version.ref = "androidx-tracingPerfetto" }
androidx-tracing-perfetto-binary = { module = "androidx.tracing:tracing-perfetto-binary", version.ref = "androidx-tracingPerfettoBinary" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidxWear" }
androidx-wear-phone-interactions = { module = "androidx.wear:wear-phone-interactions", version.ref = "androidxPhoneInteractions" }
androidx-wear-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "androidxprotolayout" }
androidx-wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "androidxRemoteInteractions" }
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidxtiles" }
androidx-wear-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidxtiles" }
androidx-wear-tiles-testing = { module = "androidx.wear.tiles:tiles-testing", version.ref = "androidxtiles" }
androidx-wear-tiles-tooling-preview = { module = "androidx.wear.tiles:tiles-tooling-preview", version.ref = "tiles-tooling-preview" }
androidx-wear-tiles-tooling = { module = "androidx.wear.tiles:tiles-tooling", version.ref = "tiles-tooling-preview" }
androidx-wear-tooling-preview = { module = "androidx.wear:wear-tooling-preview", version.ref = "wearToolingPreview" }
androidx-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidxWork" }
annotation = { module = "androidx.test:annotation", version.ref = "annotation" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "io-coil-kt" }
coil-base = { module = "io.coil-kt:coil-compose-base", version.ref = "io-coil-kt" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "io-coil-kt" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "io-coil-kt" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "com-squareup-okhttp3" }
compose-bom = "androidx.compose:compose-bom:2024.05.00"
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-material" }
compose-foundation-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose-material" }
compose-material-iconscore = { module = "androidx.compose.material:material-icons-core", version.ref = "androidx-compose-material" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
compose-material-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "androidx-compose-material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" } # version 2023.10.01 from BOM is crashing
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose-material" }
dagger-hiltandroid = { module = "com.google.dagger:hilt-android", version.ref = "googledagger" }
dagger-hiltandroidcompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "googledagger" }
dagger-hiltandroidplugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "googledagger" }
dagger-hiltandroidtesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "googledagger" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradleMavenPublishPlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradlePublishPlugin" }
hilt-ext-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
hilt-ext-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
hilt-navigationcompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
io-grpc-protobuf-lite = "io.grpc:grpc-protobuf-lite:1.63.0"
io-grpc-grpc-kotlin = "io.grpc:grpc-kotlin-stub:1.4.1"
io-grpc-grpc-android = "io.grpc:grpc-android:1.63.0"
io-grpc-grpc-binder = "io.grpc:grpc-binder:1.63.0"
google-generativeai = "com.google.ai.client.generativeai:generativeai:0.4.0"
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-playservices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutine" }
lottie-compose = "com.airbnb.android:lottie-compose:6.4.0"
mikepenz-markdown = "com.mikepenz:multiplatform-markdown-renderer:0.16.0"
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
playservices-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
playservices-base = "com.google.android.gms:play-services-base:18.4.0"
playservices-wearable = "com.google.android.gms:play-services-wearable:18.1.0"
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
retrofit2-convertermoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "com-squareup-retrofit2" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "org-robolectric" }
robolectric-shadows = { module = "org.robolectric:shadows-framework", version.ref = "org-robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-painter = { group = "io.github.takahirom.roborazzi", name = "roborazzi-painter", version.ref = "roborazzi" }
roborazzi-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "app-cash-turbine" }
wearcompose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearcompose" }
wearcompose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearcompose" }
wearcompose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearcompose" }
wearcompose-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "wearcompose" }
androidx-wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wearInput" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
gradleMavenPublishPlugin = { id = "com.vanniktech.maven.publish", version.ref = "gradlePublishPlugin" }
kotlinGradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = "com.google.protobuf:0.9.4"
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
metalavaGradle = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalava" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
