name: Fixups

on:
  workflow_dispatch:

jobs:
  fixes:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          lfs: 'true'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Reformat
        uses: gradle/gradle-build-action@v3
        with:
          arguments: spotlessApply

      - name: Push reformatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '**/*.kt'
          disable_globbing: true
          commit_message: "ðŸ¤– reformat"

      - name: Generate APIs
        uses: gradle/gradle-build-action@v3
        with:
          arguments: metalavaGenerateSignature metalavaGenerateSignatureDebug

      - name: Push new apis
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '**/current.api'
          disable_globbing: true
          commit_message: "ðŸ¤– metalava"

      - name: Repair screenshots
        uses: gradle/gradle-build-action@v3
        with:
          arguments: verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ always() }}
        with:
          file_pattern: '**/snapshots/images/*.png **/screenshots/*.png'
          disable_globbing: true
          commit_message: "ðŸ¤– Updates screenshots"
