name: Fixups

on:
  workflow_dispatch:

jobs:
  fixes:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          lfs: 'true'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Reformat
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --continue spotlessApply

      - name: Push reformatted code
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: '**/*.kt'
          disable_globbing: true
          commit_message: "ðŸ¤– reformat"

      - name: Generate APIs
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --continue metalavaGenerateSignature metalavaGenerateSignatureRelease

      - name: Push new apis
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: '**/current.api'
          disable_globbing: true
          commit_message: "ðŸ¤– metalava"

      - name: Repair screenshots
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --continue verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v6
        if: ${{ always() }}
        with:
          file_pattern: '**/snapshots/images/*.png **/screenshots/*.png **/audit/*.png'
          disable_globbing: true
          commit_message: "ðŸ¤– Updates screenshots"
